### ISSUE TITLE
Asking for instructions/general setup: How does this work with Unity? 

### ISSUE THREAD

**Issue by ssaigarimella** [huskyroboticsteam/Simulator#20]
Hi, thanks for creating the Husky simulator for Unity. Can you please explain how I would use this in my Unity 3D developer? What does rover server mean? Can I run this as a standalone package, not connected to any servers, to simulate within Unity? Thanks.

**Comment by huttongrabiel** [comment]
Hey. This code is very specific to the Husky Robotics Team at University of Washington in order to test our rover in a simulator before hardware. Therefore, there is no use case outside of that.
